# Introduction to Risk Management with Derivatives

**Definition:** Derivatives are financial instruments used to manage and hedge various types of risk.

**Purpose:** Protect portfolios from adverse price movements, interest rate changes, and other risks.

**Importance:** Essential for maintaining portfolio stability and achieving financial goals.


# Types of Derivatives for Risk Management

**Options:** Contracts that give the right, but not the obligation, to buy or sell an asset at a predetermined price.

**Futures:** Contracts obligating the buyer to purchase, or the seller to sell, an asset at a predetermined future date and price.

**Forwards:** Similar to futures but customized and traded over-the-counter.

**Swaps:** Contracts to exchange cash flows or other financial instruments between two parties.


# Hedging with Options

**Protective Put:** Buying a put option to protect against a decline in the value of an asset.

**Covered Call:** Selling a call option while holding the underlying asset to generate income.

**Benefits:** Provides downside protection while allowing for upside potential.


# Practical Example

**Scenario:** Protect the value of a stock investment using a put option.

**Steps:**

1. Identify the stock and its current price.
2. Select a put option with an appropriate strike price and expiration date.
3. Calculate the cost and potential outcomes of the strategy.


In [4]:
# Example data
stock_price = 100  # Current stock price
strike_price = 95  # Strike price of the put option
premium = 3        # Premium paid for the put option

# Calculate potential outcomes
loss_without_put = stock_price - strike_price  # Loss if the stock price drops to the strike price
loss_with_put = loss_without_put + premium     # Loss including the cost of the put option

print(f"Loss without Protective Put: ${loss_without_put:.2f}")
print(f"Loss with Protective Put: ${loss_with_put:.2f}")


Loss without Protective Put: $5.00
Loss with Protective Put: $8.00


# Explanation of Results

In this practical example, we calculated the potential losses with and without a protective put option. The "Loss without Protective Put" shows the loss you would incur if the stock price drops to the strike price without any form of protection. 

In this case, the loss is $5.00, which is the difference between the current stock price ($100) and the strike price ($95). 

The "Loss with Protective Put" includes the premium paid for the put option. Here, the loss is $8.00, which adds the $3.00 premium to the $5.00 loss, showing the total cost of having the protective put in place.

This result is expected and demonstrates the trade-off when using a protective put: you reduce the downside risk but incur an additional cost in the form of the option premium. This cost is the price of the "insurance" against larger potential losses, and it's a strategic decision in risk management to protect against significant declines in the value of an asset.


# Practical Example: Worthwhile Option Scenario

## Scenario
Consider a scenario where you want to protect the value of your stock investment using a put option. We will calculate the potential losses with and without a protective put to see if the option actually reduces your loss.

### Steps:
1. Identify the stock and its current price.
2. Select a put option with an appropriate strike price and expiration date.
3. Calculate the cost and potential outcomes of the strategy if the stock price drops below the strike price.



In [5]:
# Example data
stock_price = 100   # Current stock price
strike_price = 90   # Strike price of the put option
premium = 5         # Premium paid for the put option

# Calculate potential outcomes assuming the stock price drops significantly
new_stock_price = 80  # Stock price after a significant drop

# Calculate losses
loss_without_put = stock_price - new_stock_price  # Loss without the protective put
loss_with_put = (strike_price - new_stock_price) + premium  # Loss with protective put (including the cost of the premium)

print(f"Loss without Protective Put: ${loss_without_put:.2f}")
print(f"Loss with Protective Put: ${loss_with_put:.2f}")



Loss without Protective Put: $20.00
Loss with Protective Put: $15.00


# Explanation of Results

In this scenario, the stock price drops significantly from $100 to $80, and the protective put option has a strike price of $90.

- **Loss without Protective Put:** The loss without any protection is $20.00, which is the difference between the original stock price ($100) and the new stock price ($80).

- **Loss with Protective Put:** With the protective put option, the loss is reduced to $15.00. This loss includes the difference between the strike price ($90) and the new stock price ($80), plus the $5.00 premium paid for the put option.

### Worthwhile Consideration:
In this case, the protective put was worthwhile because it reduced the loss from $20.00 to $15.00. The protective put option effectively limited the downside risk, providing financial protection and making the strategy beneficial in this situation.
